In [2]:
import sys
import numpy as np
#.1 השתמש בפקודת arange, צור והדפס מערך עם המספרים:
#a. מ- 1-10
np.arange(1 , 10 + 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#b. מ- 0.5 ועד 5 בדילוגים של 0.25
np.arange(0.5 , 5 + 0.25 , 0.25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [8]:
#.2 השתמש בפקודת zeros, צור והדפס מערך של אפסים בגודל הבא:
#a. מערך של 10 איברים בשורה 1
print(np.zeros(10, dtype=int))


[0 0 0 0 0 0 0 0 0 0]


In [14]:
#b. מערך של 12 איברים בגדול 4 X 3
sh = np.arange(0, 12)
np.reshape(sh, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#.3 השתמש בפקודת linspace, צור והדפס מערך של מספרים:
#a. בגודל 5 איברים מ 2 ועד 12
print(np.linspace(2, 12 , 5, dtype=int))

[ 2  4  7  9 12]


In [18]:
#b. בגודל 4 איברים מ 3 ועד 9
print(np.linspace(3,9,4,dtype=int))

[3 5 7 9]


In [28]:
#.4 השתמש בפקודת random np, צור והדפס מערך של מספרים אקראיים:
#a. בגודל 2 X 4 אשר כל מספר אקראי הוא בין 0 לבין 0.999
randy_a = np.random.rand(4, 2) * 0.999
print(randy_a)

[[0.96860507 0.47867484]
 [0.17615364 0.03311327]
 [0.40355861 0.44466985]
 [0.9062583  0.18618171]]


In [26]:
#b. בגודל 3 X 3 אשר כל מספר אקראי הוא שלם בין 10 לבין 20
randy = np.random.rand(3, 3) *10+ 10
print(randy.astype(int))

[[18 19 17]
 [18 19 12]
 [11 16 17]]


In [30]:
#באמצעות reshape שנה את גודל המערך שיצרת בסעיף a ל 8 X .1
np.reshape( randy_a , (1, 8))
#מה צריך לשים לב כאשר משתמשים בפעולת reshape ?
'''משנה את הצורה של המידע אבל לא את הכמות שלו, ודורש תשומת לב לתצוגות מול עותקים.'''

'משנה את הצורה של המידע אבל לא את הכמות שלו, ודורש תשומת לב לתצוגות מול עותקים.'

In [ ]:
#.5 מה יתקבל אם נגריל מספרים אקראים תוך שימוש ב- seed קבוע?
"""יתקבלו אותם המספרים בכל פעם שנריץ את הקוד שונה מהמצב הרגיל בו המספרים ישתנו בצורה אקראית כל פעם."""
#מה היתרון של השימוש ב- seed?
"""הוא מבטיח שהתוצאות האקראיות יהיו זהות בכל הרצה של הקוד,מה שעוזר לנו לבדוק ולשחזר קודים לבדיקה"""